version: "3.8"

services:
  inquisitors-server:
    build:
      context: .
      target: server
    container_name: inquisitors_server
    command: python -u -m inquisitors-server
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./log:/log
